## Examining EcoMove Data

### Data investigation and preparation

In [2]:
# Author: Mike Allen 25119947
import sys
import pandas as pd
import numpy as np
import streamlit as st
import plotly_express as px

In [3]:
print(f"Python Version: {sys.version}")
print(f"Pandas Version: {pd.__version__}")
print(f"NumPy Version: {np.__version__}")
print(f"Streamlit Verion: {st.__version__}")
print(f"Plotly Version: {px.__version__}")

Python Version: 3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:11:29) [Clang 20.1.8 ]
Pandas Version: 2.3.3
NumPy Version: 2.3.5
Streamlit Verion: 1.58.0
Plotly Version: 0.4.1

In [ ]:
# loading the data
df = pd.read_excel('[5442] EcoMoveMobility.xlsx', sheet_name='Dataset', header=0, index_col=0)

In [5]:
df.head()

,Date,City,Country,Transport_Mode,Route_Type,Weather,Event_Day,Passengers,Trips,Average_Delay_Minutes,On_Time_Percentage,Ticket_Revenue_EUR,Operating_Cost_EUR,CO2_Saved_KG,Energy_Consumption_KWh,Customer_Rating,Accessibility_Complaints
Record_ID,,,,,,,,,,,,,,,,,
EM-00001,45747,Paris,France,Tram,Tourist Zone,Cloudy,Yes,22946,101,3.2,85.1,58846.34,47796.73,2005.0,1446.4,4.4,26
EM-00002,45717,Paris,France,Tram,University Area,Cloudy,No,9417,59,1.5,90.1,24578.85,20708.01,824.3,495.1,4.7,7
EM-00003,45882,Rotterdam,Netherlands,Tram,Airport Connector,Clear,No,6467,38,3.4,87.9,15168.68,14129.41,693.1,405.8,4.4,7
EM-00004,45504,Lyon,France,Tram,University Area,Clear,Yes,5218,33,6.9,74.5,14172.20,11945.52,600.1,278.1,3.9,7
EM-00005,45578,Amsterdam,Netherlands,Metro,Tourist Zone,Cloudy,No,10258,19,3.6,83.2,27534.92,28846.82,1392.4,580.5,4.4,12

In [6]:
# Convert Excel serial date to datetime
df['Date'] = pd.to_datetime(df['Date'], unit='D', origin='1899-12-30')

In [7]:
df.head(20)

,Date,City,Country,Transport_Mode,Route_Type,Weather,Event_Day,Passengers,Trips,Average_Delay_Minutes,On_Time_Percentage,Ticket_Revenue_EUR,Operating_Cost_EUR,CO2_Saved_KG,Energy_Consumption_KWh,Customer_Rating,Accessibility_Complaints
Record_ID,,,,,,,,,,,,,,,,,
EM-00001,2025-03-31,Paris,France,Tram,Tourist Zone,Cloudy,Yes,22946,101,3.2,85.1,58846.34,47796.73,2005.0,1446.4,4.4,26
EM-00002,2025-03-01,Paris,France,Tram,University Area,Cloudy,No,9417,59,1.5,90.1,24578.85,20708.01,824.3,495.1,4.7,7
EM-00003,2025-08-13,Rotterdam,Netherlands,Tram,Airport Connector,Clear,No,6467,38,3.4,87.9,15168.68,14129.41,693.1,405.8,4.4,7
EM-00004,2024-07-31,Lyon,France,Tram,University Area,Clear,Yes,5218,33,6.9,74.5,14172.20,11945.52,600.1,278.1,3.9,7
EM-00005,2024-10-13,Amsterdam,Netherlands,Metro,Tourist Zone,Cloudy,No,10258,19,3.6,83.2,27534.92,28846.82,1392.4,580.5,4.4,12
EM-00006,2025-03-13,Vienna,Austria,E-Scooter,Commuter Corridor,Rain,No,394,394,4.7,84.1,563.40,10583.52,59.1,8.2,3.8,0
EM-00007,2024-10-16,Rotterdam,Netherlands,Park and Ride,Commuter Corridor,Clear,No,4540,35,3.5,82.9,14235.98,10442.58,281.9,154.3,4.1,8
EM-00008,2025-06-07,Paris,France,Bike Share,Suburban Feeder,Heatwave,No,349,349,2.1,88.2,366.88,3157.01,62.1,0.0,3.8,1
EM-00009,2025-06-20,Lyon,France,Metro,University Area,Cloudy,No,27141,47,5.3,82.5,82198.10,70188.14,3688.0,1299.9,4.3,68
EM-00010,2025-08-03,Amsterdam,Netherlands,Tram,Airport Connector,Cloudy,No,4559,27,2.5,91.2,10399.10,9517.96,534.1,243.6,4.5,4
EM-00011,2025-12-24,Rome,Italy,E-Scooter,Tourist Zone,Cloudy,No,159,159,1.1,89.5,256.72,4340.28,20.6,3.0,4.4,0
EM-00012,2025-03-06,Lyon,France,Bus,Tourist Zone,Clear,No,3568,41,6.7,74.6,8526.67,7804.35,328.9,299.4,3.7,5
EM-00013,2024-05-23,Rome,Italy,Bus,University Area,Clear,No,2570,34,6.7,75.9,5483.92,6269.73,179.1,173.2,3.9,1
EM-00014,2025-01-21,Milan,Italy,Metro,Airport Connector,Cloudy,No,16824,37,3.0,87.1,52285.19,40710.62,2311.1,829.9,4.1,38
EM-00015,2024-09-27,Paris,France,Metro,University Area,Cloudy,No,18951,38,4.9,79.6,54688.52,53815.13,2413.6,987.3,3.7,27
EM-00016,2024-07-19,Milan,Italy,Tram,University Area,Heatwave,No,5414,29,5.9,77.6,11930.18,10276.68,470.5,293.3,4.0,7
EM-00017,2025-07-01,Amsterdam,Netherlands,Park and Ride,Tourist Zone,Snow,No,3195,29,7.6,72.6,10383.95,7315.00,214.2,118.4,3.4,6
EM-00018,2024-11-22,Lyon,France,Metro,Suburban Feeder,Cloudy,No,18779,44,2.7,86.5,55319.10,54640.65,2617.2,1089.8,4.1,37
EM-00019,2025-09-16,Milan,Italy,Bike Share,Airport Connector,Clear,No,474,474,0.0,96.7,596.16,14858.25,72.8,0.0,4.5,1
EM-00020,2024-09-03,Milan,Italy,Bus,Commuter Corridor,Clear,No,5658,55,6.4,77.8,13186.39,14234.67,509.0,488.2,4.1,4

In [8]:
print(df.columns)

Index(['Date', 'City', 'Country', 'Transport_Mode', 'Route_Type', 'Weather',
       'Event_Day', 'Passengers', 'Trips', 'Average_Delay_Minutes',
       'On_Time_Percentage', 'Ticket_Revenue_EUR', 'Operating_Cost_EUR',
       'CO2_Saved_KG', 'Energy_Consumption_KWh', 'Customer_Rating',
       'Accessibility_Complaints'],
      dtype='object')

In [9]:
df.shape

(5000, 17)

In [10]:
# Check for duplicates in the data
row_duplicates = df.duplicated()
col_duplicates = df.columns.duplicated()

print(f"Number of duplicate rows: {row_duplicates.sum()}")
print(f"Number of dupicate columns {col_duplicates.sum()}")

Number of duplicate rows: 0
Number of dupicate columns 0

In [11]:
#check for missing values in the entire DataFrame
df.isnull().sum()

Date                        0
City                        0
Country                     0
Transport_Mode              0
Route_Type                  0
Weather                     0
Event_Day                   0
Passengers                  0
Trips                       0
Average_Delay_Minutes       0
On_Time_Percentage          0
Ticket_Revenue_EUR          0
Operating_Cost_EUR          0
CO2_Saved_KG                0
Energy_Consumption_KWh      0
Customer_Rating             0
Accessibility_Complaints    0
dtype: int64

In [12]:
#show all the categorical columns with missing values
categorical_cols = df.select_dtypes(include=['object']).columns
missing_values = df[categorical_cols].isnull().sum()
if missing_values[missing_values > 0].empty:
    print("No categorical columns with missing values.")
else:
    print("Categorical columns with missing values:")
    print(missing_values[missing_values > 0])

No categorical columns with missing values.

In [13]:
#show all the numerical columns with missing values
numerical_cols = df.select_dtypes(include=[np.number]).columns
missing_values = df[numerical_cols].isnull().sum()
if missing_values[missing_values > 0].empty:
    print("No numerical columns with missing values.")
else:
    print("Numerical columns with missing values:")
    print(missing_values[missing_values > 0])

No numerical columns with missing values.

In [14]:
df.dtypes

Date                        datetime64[ns]
City                                object
Country                             object
Transport_Mode                      object
Route_Type                          object
Weather                             object
Event_Day                           object
Passengers                           int64
Trips                                int64
Average_Delay_Minutes              float64
On_Time_Percentage                 float64
Ticket_Revenue_EUR                 float64
Operating_Cost_EUR                 float64
CO2_Saved_KG                       float64
Energy_Consumption_KWh             float64
Customer_Rating                    float64
Accessibility_Complaints             int64
dtype: object

In [15]:
df.describe()

,Date,Passengers,Trips,Average_Delay_Minutes,On_Time_Percentage,Ticket_Revenue_EUR,Operating_Cost_EUR,CO2_Saved_KG,Energy_Consumption_KWh,Customer_Rating,Accessibility_Complaints
count,5000,5000.000000,5000.00000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2024-12-27 20:49:55.200000,8181.944200,121.77240,4.35332,82.057360,22328.122852,22422.003194,896.394860,466.808360,4.008400,12.532200
min,2024-01-01 00:00:00,64.000000,11.00000,0.00000,55.000000,90.930000,978.370000,8.300000,0.000000,2.700000,0.000000
25%,2024-07-01 00:00:00,1411.750000,36.00000,2.60000,76.500000,3280.330000,7189.860000,126.850000,85.200000,3.700000,2.000000
50%,2024-12-22 00:00:00,4398.000000,52.00000,4.40000,82.000000,11190.020000,11638.285000,338.300000,269.700000,4.000000,7.000000
75%,2025-06-27 00:00:00,10077.500000,106.00000,6.00000,87.900000,26329.652500,22732.975000,1009.475000,599.625000,4.300000,15.000000
max,2025-12-31 00:00:00,66416.000000,1048.00000,12.50000,99.000000,204386.050000,178936.390000,8884.100000,3856.300000,4.900000,147.000000
std,NaN,10018.716968,155.78715,2.38625,7.934777,28822.411230,26114.317880,1261.161021,564.215549,0.399742,16.967373

In [16]:
# Check for skewnes and kurtosis in numerical columns
skewness = df[numerical_cols].skew()
kurtosis = df[numerical_cols].kurtosis()

# Display skewness and kurtosis
print("Skewness of numerical columns:")
print(skewness)
print("\nKurtosis of numerical columns:")
print(kurtosis)

Skewness of numerical columns:
Passengers                  1.901019
Trips                       2.134868
Average_Delay_Minutes       0.161689
On_Time_Percentage         -0.147955
Ticket_Revenue_EUR          1.945992
Operating_Cost_EUR          2.147367
CO2_Saved_KG                2.086888
Energy_Consumption_KWh      1.852165
Customer_Rating            -0.244228
Accessibility_Complaints    2.587787
dtype: float64

Kurtosis of numerical columns:
Passengers                  3.570937
Trips                       4.180220
Average_Delay_Minutes      -0.395980
On_Time_Percentage         -0.359795
Ticket_Revenue_EUR          3.719723
Operating_Cost_EUR          4.595891
CO2_Saved_KG                4.265726
Energy_Consumption_KWh      3.523079
Customer_Rating            -0.222692
Accessibility_Complaints    8.104361
dtype: float64

In [17]:
# plot the skewness and kurtosis with kde for the whole dataset
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
df[numerical_cols].plot(kind='kde', subplots=True, layout=(len(numerical_cols)//2 + len(numerical_cols)%2, 2),
                         figsize=(12, 6))
plt.tight_layout()
plt.show()

/var/folders/wf/_1lvp0fx2q12ycft4t95_wz00000gn/T/ipykernel_18545/435643200.py:8: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [18]:
# Create boxplots as subplots for each numerical column to visualize the distribution and identify outliers
df[numerical_cols].plot(kind='box', subplots=True, layout=(len(numerical_cols)//2 + len(numerical_cols)%2, 2),
                            figsize=(12, 6), title='Boxplots of Numerical Columns')
plt.tight_layout()
plt.show()

/var/folders/wf/_1lvp0fx2q12ycft4t95_wz00000gn/T/ipykernel_18545/2455279784.py:5: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## What's the story?

### Defining the purpose

- Audience: Senior managers of the EcoMove City Transport Authority
- Business Goals: Your analysis should explore how sustainable urban mobility performance varies across time, cities, countries, transport modes, weather conditions, major event days, and route types. 
- Questions: The organisation is particularly interested in identifying high-demand cities, weak-performing transport modes, delay patterns, accessibility issues, cost and revenue performance, customer satisfaction, and environmental impact.
- Dashboard Review: Unknown

### Additional Requirements

1.	A time-series visualisation to show mobility trends over time
2.	A comparison chart to compare cities, countries, route types, or transport modes
3.	A relationship-based visualisation, such as a scatter plot or correlation heatmap
4.	A distribution-based visualisation, such as a histogram, box plot, or violin plot
5.	A performance indicator visualisation showing measures such as revenue, cost, delays, satisfaction, demand, or CO2 saved
6.	A dashboard visualisation combining multiple views with interactive filters

In [19]:
#Exporting the cleaned and prepared dataset for use in the interactive dashboard
df.to_excel('cleaned_ds.xlsx')
df_cleaned = pd.read_excel('cleaned_ds.xlsx')

In [20]:
df_cleaned.head()

,Record_ID,Date,City,Country,Transport_Mode,Route_Type,Weather,Event_Day,Passengers,Trips,Average_Delay_Minutes,On_Time_Percentage,Ticket_Revenue_EUR,Operating_Cost_EUR,CO2_Saved_KG,Energy_Consumption_KWh,Customer_Rating,Accessibility_Complaints
0,EM-00001,2025-03-31,Paris,France,Tram,Tourist Zone,Cloudy,Yes,22946,101,3.2,85.1,58846.34,47796.73,2005.0,1446.4,4.4,26
1,EM-00002,2025-03-01,Paris,France,Tram,University Area,Cloudy,No,9417,59,1.5,90.1,24578.85,20708.01,824.3,495.1,4.7,7
2,EM-00003,2025-08-13,Rotterdam,Netherlands,Tram,Airport Connector,Clear,No,6467,38,3.4,87.9,15168.68,14129.41,693.1,405.8,4.4,7
3,EM-00004,2024-07-31,Lyon,France,Tram,University Area,Clear,Yes,5218,33,6.9,74.5,14172.20,11945.52,600.1,278.1,3.9,7
4,EM-00005,2024-10-13,Amsterdam,Netherlands,Metro,Tourist Zone,Cloudy,No,10258,19,3.6,83.2,27534.92,28846.82,1392.4,580.5,4.4,12

In [21]:
df_cleaned.columns

Index(['Record_ID', 'Date', 'City', 'Country', 'Transport_Mode', 'Route_Type',
       'Weather', 'Event_Day', 'Passengers', 'Trips', 'Average_Delay_Minutes',
       'On_Time_Percentage', 'Ticket_Revenue_EUR', 'Operating_Cost_EUR',
       'CO2_Saved_KG', 'Energy_Consumption_KWh', 'Customer_Rating',
       'Accessibility_Complaints'],
      dtype='object')

### 1. A time-series visualisation to show mobility trends over time

In [22]:
#Create a time series visualisation to show mobility trends over time, grouping by month and year, 
    #and using the Date column as the x-axis and the trips as the y-axis.
import plotly.express as px

df_cleaned['Date'] = pd.to_datetime(df_cleaned['Date'])
df_cleaned['Year'] = df_cleaned['Date'].dt.year
df_cleaned['Month'] = df_cleaned['Date'].dt.month
time_series_df = df_cleaned.groupby(['Year', 'Month'])['Trips'].sum().reset_index()

fig = px.line(
    time_series_df,
    x="Month",
    y="Trips",
    color="Year",
    markers=True,
)

fig.update_layout(
    title="Mobility Trends Over Time",
    xaxis_title="Month",
    yaxis_title="Trips",
)

fig.show()

In [23]:
# Create a histogram to show the average delay in minutes for each mode of transport, using the Mode column 
# as the x-axis and the average delay as the y-axis.

# Convert the delay column to numeric
delay = pd.to_numeric(
    df["Average_Delay_Minutes"],
    errors="coerce"
).dropna()

histogram_data = pd.DataFrame({
    "Delay": delay
})

fig = px.histogram(
    histogram_data,
    x="Delay",
    nbins=26,
    title="Distribution of Delays in Minutes",
    labels={
        "Delay": "Delay (minutes)",
        "count": "Frequency"
    },
    template="plotly_white"
)

fig.update_traces(
    marker_color="#44bd32",
    marker_line_color="black",
    marker_line_width=1
)

fig.update_layout(
    xaxis_title="Delay (minutes)",
    yaxis_title="Frequency",
    bargap=0.05,
    height=500
)

### 2. A comparison chart to compare cities, countries, route types, or transport modes

In [24]:
# Total trips by route type and transport mode, grouped by city and country, using a bar chart to visualize the data.
grouped_df = (
df_cleaned.groupby(['Route_Type', 'Transport_Mode', 'City', 'Country'], as_index=False)
.agg({'Trips': 'sum'})
)

fig = px.bar(
    grouped_df,
    x="Route_Type",
    y="Trips",
    color="Transport_Mode",
    barmode="group"
)

fig.update_layout(
    xaxis_title="Route Type",
    yaxis_title="Total Trips",
)

fig.update_traces(
    marker_line_color="black", 
    marker_line_width=0.1)

fig.show()

In [25]:
# Operating Cost by Transport Type and Trips
grouped_df = (
    df_cleaned.groupby(['Operating_Cost_EUR', 'Transport_Mode', 'City'], as_index=False)
    .agg({'Operating_Cost_EUR': 'sum'})
)

fig = px.bar(
    grouped_df,
    x="City",
    y="Operating_Cost_EUR",
    color="Transport_Mode",
    barmode="group"
)

fig.update_layout(
    xaxis_title="Operating_Cost_EUR",
    yaxis_title="Total Trips",
)

fig.update_traces(marker_line_color="black", marker_line_width=0.1)


fig.show()

In [26]:
# Operating cost by City and Transport_Mode
financial_df = df_cleaned[["City", "Transport_Mode", "Operating_Cost_EUR"]]

fig = px.histogram(
    financial_df,
    x="City",
    y="Operating_Cost_EUR",
    color="Transport_Mode",
    title="Operating Cost by City and Transport Mode",
    labels={
        "City": "City",
        "Operating_Cost_EUR": "Operating Cost (€)",
        "Transport_Mode": "Transport Mode"
    },
    template="plotly_white"
)
fig.show()

In [27]:
# Operating Cost by City
financial_df = df_cleaned[["City",
                "Operating_Cost_EUR"]]

fig = px.histogram(
financial_df,
x="City",
y="Operating_Cost_EUR",
color='City',
title="Operating Cost by City",
labels={
    "City": "City",
    "Operating_Cost_EUR": "Operating Cost (€)"
},
template="plotly_white"
)

fig.update_traces(
selector=dict(mode="markers"),
marker=dict(size=5, opacity=0.75)
)

fig.update_layout(
height=500,
yaxis=dict(tickprefix="€", tickformat=",.0f")
)

fig.show()

In [28]:
#Get the city list
cities = df_cleaned['City'].unique()
cities

array(['Paris', 'Rotterdam', 'Lyon', 'Amsterdam', 'Vienna', 'Rome',
       'Milan', 'Munich', 'Hamburg', 'Barcelona', 'Berlin', 'Madrid'],
      dtype=object)

In [29]:
# Overall distribution of transport type (All Journeys)

transport_counts = (
df_cleaned["Transport_Mode"]
.value_counts()
.reindex(
    ["Bike Share", "Bus", "E-Scooter", "Metro", "Park and Ride", "Tram"],
    fill_value=0
)
.reset_index()
)


fig.update_traces(
    textposition="inside",
    textinfo="label+percent"
)

fig.update_layout(
    title="Overall Distribution of Transport Type (All Journeys)"
)

fig.show()

ValueError: Invalid property specified for object of type plotly.graph_objs.Histogram: 'textinfo'

Did you mean "text"?

    Valid properties:
        alignmentgroup
            Set several traces linked to the same position axis or
            matching axes to the same alignmentgroup. This controls
            whether bars compute their positional range dependently
            or independently.
        autobinx
            Obsolete: since v1.42 each bin attribute is auto-
            determined separately and `autobinx` is not needed.
            However, we accept `autobinx: true` or `false` and will
            update `xbins` accordingly before deleting `autobinx`
            from the trace.
        autobiny
            Obsolete: since v1.42 each bin attribute is auto-
            determined separately and `autobiny` is not needed.
            However, we accept `autobiny: true` or `false` and will
            update `ybins` accordingly before deleting `autobiny`
            from the trace.
        bingroup
            Set a group of histogram traces which will have
            compatible bin settings. Note that traces on the same
            subplot and with the same "orientation" under `barmode`
            "stack", "relative" and "group" are forced into the
            same bingroup, Using `bingroup`, traces under `barmode`
            "overlay" and on different axes (of the same axis type)
            can have compatible bin settings. Note that histogram
            and histogram2d* trace can share the same `bingroup`
        cliponaxis
            Determines whether the text nodes are clipped about the
            subplot axes. To show the text nodes above axis lines
            and tick labels, make sure to set `xaxis.layer` and
            `yaxis.layer` to *below traces*.
        constraintext
            Constrain the size of text inside or outside a bar to
            be no larger than the bar itself.
        cumulative
            :class:`plotly.graph_objects.histogram.Cumulative`
            instance or dict with compatible properties
        customdata
            Assigns extra data each datum. This may be useful when
            listening to hover, click and selection events. Note
            that, "scatter" traces also appends customdata items in
            the markers DOM elements
        customdatasrc
            Sets the source reference on Chart Studio Cloud for
            `customdata`.
        error_x
            :class:`plotly.graph_objects.histogram.ErrorX` instance
            or dict with compatible properties
        error_y
            :class:`plotly.graph_objects.histogram.ErrorY` instance
            or dict with compatible properties
        histfunc
            Specifies the binning function used for this histogram
            trace. If "count", the histogram values are computed by
            counting the number of values lying inside each bin. If
            "sum", "avg", "min", "max", the histogram values are
            computed using the sum, the average, the minimum or the
            maximum of the values lying inside each bin
            respectively.
        histnorm
            Specifies the type of normalization used for this
            histogram trace. If "", the span of each bar
            corresponds to the number of occurrences (i.e. the
            number of data points lying inside the bins). If
            "percent" / "probability", the span of each bar
            corresponds to the percentage / fraction of occurrences
            with respect to the total number of sample points
            (here, the sum of all bin HEIGHTS equals 100% / 1). If
            "density", the span of each bar corresponds to the
            number of occurrences in a bin divided by the size of
            the bin interval (here, the sum of all bin AREAS equals
            the total number of sample points). If *probability
            density*, the area of each bar corresponds to the
            probability that an event will fall into the
            corresponding bin (here, the sum of all bin AREAS
            equals 1).
        hoverinfo
            Determines which trace information appear on hover. If
            `none` or `skip` are set, no information is displayed
            upon hovering. But, if `none` is set, click and hover
            events are still fired.
        hoverinfosrc
            Sets the source reference on Chart Studio Cloud for
            `hoverinfo`.
        hoverlabel
            :class:`plotly.graph_objects.histogram.Hoverlabel`
            instance or dict with compatible properties
        hovertemplate
            Template string used for rendering the information that
            appear on hover box. Note that this will override
            `hoverinfo`. Variables are inserted using %{variable},
            for example "y: %{y}" as well as %{xother}, {%_xother},
            {%_xother_}, {%xother_}. When showing info for several
            points, "xother" will be added to those with different
            x positions from the first point. An underscore before
            or after "(x|y)other" will add a space on that side,
            only when this field is shown. Numbers are formatted
            using d3-format's syntax %{variable:d3-format}, for
            example "Price: %{y:$.2f}".
            https://github.com/d3/d3-format/tree/v1.4.5#d3-format
            for details on the formatting syntax. Dates are
            formatted using d3-time-format's syntax
            %{variable|d3-time-format}, for example "Day:
            %{2019-01-01|%A}". https://github.com/d3/d3-time-
            format/tree/v2.2.3#locale_format for details on the
            date formatting syntax. The variables available in
            `hovertemplate` are the ones emitted as event data
            described at this link
            https://plotly.com/javascript/plotlyjs-events/#event-
            data. Additionally, every attributes that can be
            specified per-point (the ones that are `arrayOk: true`)
            are available. Finally, the template string has access
            to variable `binNumber` Anything contained in tag
            `<extra>` is displayed in the secondary box, for
            example `<extra>%{fullData.name}</extra>`. To hide the
            secondary box completely, use an empty tag
            `<extra></extra>`.
        hovertemplatesrc
            Sets the source reference on Chart Studio Cloud for
            `hovertemplate`.
        hovertext
            Same as `text`.
        hovertextsrc
            Sets the source reference on Chart Studio Cloud for
            `hovertext`.
        ids
            Assigns id labels to each datum. These ids for object
            constancy of data points during animation. Should be an
            array of strings, not numbers or any other type.
        idssrc
            Sets the source reference on Chart Studio Cloud for
            `ids`.
        insidetextanchor
            Determines if texts are kept at center or start/end
            points in `textposition` "inside" mode.
        insidetextfont
            Sets the font used for `text` lying inside the bar.
        legend
            Sets the reference to a legend to show this trace in.
            References to these legends are "legend", "legend2",
            "legend3", etc. Settings for these legends are set in
            the layout, under `layout.legend`, `layout.legend2`,
            etc.
        legendgroup
            Sets the legend group for this trace. Traces and shapes
            part of the same legend group hide/show at the same
            time when toggling legend items.
        legendgrouptitle
            :class:`plotly.graph_objects.histogram.Legendgrouptitle
            ` instance or dict with compatible properties
        legendrank
            Sets the legend rank for this trace. Items and groups
            with smaller ranks are presented on top/left side while
            with "reversed" `legend.traceorder` they are on
            bottom/right side. The default legendrank is 1000, so
            that you can use ranks less than 1000 to place certain
            items before all unranked items, and ranks greater than
            1000 to go after all unranked items. When having
            unranked or equal rank items shapes would be displayed
            after traces i.e. according to their order in data and
            layout.
        legendwidth
            Sets the width (in px or fraction) of the legend for
            this trace.
        marker
            :class:`plotly.graph_objects.histogram.Marker` instance
            or dict with compatible properties
        meta
            Assigns extra meta information associated with this
            trace that can be used in various text attributes.
            Attributes such as trace `name`, graph, axis and
            colorbar `title.text`, annotation `text`
            `rangeselector`, `updatemenues` and `sliders` `label`
            text all support `meta`. To access the trace `meta`
            values in an attribute in the same trace, simply use
            `%{meta[i]}` where `i` is the index or key of the
            `meta` item in question. To access trace `meta` in
            layout attributes, use `%{data[n[.meta[i]}` where `i`
            is the index or key of the `meta` and `n` is the trace
            index.
        metasrc
            Sets the source reference on Chart Studio Cloud for
            `meta`.
        name
            Sets the trace name. The trace name appears as the
            legend item and on hover.
        nbinsx
            Specifies the maximum number of desired bins. This
            value will be used in an algorithm that will decide the
            optimal bin size such that the histogram best
            visualizes the distribution of the data. Ignored if
            `xbins.size` is provided.
        nbinsy
            Specifies the maximum number of desired bins. This
            value will be used in an algorithm that will decide the
            optimal bin size such that the histogram best
            visualizes the distribution of the data. Ignored if
            `ybins.size` is provided.
        offsetgroup
            Set several traces linked to the same position axis or
            matching axes to the same offsetgroup where bars of the
            same position coordinate will line up.
        opacity
            Sets the opacity of the trace.
        orientation
            Sets the orientation of the bars. With "v" ("h"), the
            value of the each bar spans along the vertical
            (horizontal).
        outsidetextfont
            Sets the font used for `text` lying outside the bar.
        selected
            :class:`plotly.graph_objects.histogram.Selected`
            instance or dict with compatible properties
        selectedpoints
            Array containing integer indices of selected points.
            Has an effect only for traces that support selections.
            Note that an empty array means an empty selection where
            the `unselected` are turned on for all points, whereas,
            any other non-array values means no selection all where
            the `selected` and `unselected` styles have no effect.
        showlegend
            Determines whether or not an item corresponding to this
            trace is shown in the legend.
        stream
            :class:`plotly.graph_objects.histogram.Stream` instance
            or dict with compatible properties
        text
            Sets hover text elements associated with each bar. If a
            single string, the same string appears over all bars.
            If an array of string, the items are mapped in order to
            the this trace's coordinates.
        textangle
            Sets the angle of the tick labels with respect to the
            bar. For example, a `tickangle` of -90 draws the tick
            labels vertically. With "auto" the texts may
            automatically be rotated to fit with the maximum size
            in bars.
        textfont
            Sets the text font.
        textposition
            Specifies the location of the `text`. "inside"
            positions `text` inside, next to the bar end (rotated
            and scaled if needed). "outside" positions `text`
            outside, next to the bar end (scaled if needed), unless
            there is another bar stacked on this one, then the text
            gets pushed inside. "auto" tries to position `text`
            inside the bar, but if the bar is too small and no bar
            is stacked on this one the text is moved outside. If
            "none", no text appears.
        textsrc
            Sets the source reference on Chart Studio Cloud for
            `text`.
        texttemplate
            Template string used for rendering the information text
            that appear on points. Note that this will override
            `textinfo`. Variables are inserted using %{variable},
            for example "y: %{y}". Numbers are formatted using
            d3-format's syntax %{variable:d3-format}, for example
            "Price: %{y:$.2f}".
            https://github.com/d3/d3-format/tree/v1.4.5#d3-format
            for details on the formatting syntax. Dates are
            formatted using d3-time-format's syntax
            %{variable|d3-time-format}, for example "Day:
            %{2019-01-01|%A}". https://github.com/d3/d3-time-
            format/tree/v2.2.3#locale_format for details on the
            date formatting syntax. Every attributes that can be
            specified per-point (the ones that are `arrayOk: true`)
            are available. Finally, the template string has access
            to variables `label` and `value`.
        uid
            Assign an id to this trace, Use this to provide object
            constancy between traces during animations and
            transitions.
        uirevision
            Controls persistence of some user-driven changes to the
            trace: `constraintrange` in `parcoords` traces, as well
            as some `editable: true` modifications such as `name`
            and `colorbar.title`. Defaults to `layout.uirevision`.
            Note that other user-driven trace attribute changes are
            controlled by `layout` attributes: `trace.visible` is
            controlled by `layout.legend.uirevision`,
            `selectedpoints` is controlled by
            `layout.selectionrevision`, and `colorbar.(x|y)`
            (accessible with `config: {editable: true}`) is
            controlled by `layout.editrevision`. Trace changes are
            tracked by `uid`, which only falls back on trace index
            if no `uid` is provided. So if your app can add/remove
            traces before the end of the `data` array, such that
            the same trace has a different index, you can still
            preserve user-driven changes if you give each trace a
            `uid` that stays with it as it moves.
        unselected
            :class:`plotly.graph_objects.histogram.Unselected`
            instance or dict with compatible properties
        visible
            Determines whether or not this trace is visible. If
            "legendonly", the trace is not drawn, but can appear as
            a legend item (provided that the legend itself is
            visible).
        x
            Sets the sample data to be binned on the x axis.
        xaxis
            Sets a reference between this trace's x coordinates and
            a 2D cartesian x axis. If "x" (the default value), the
            x coordinates refer to `layout.xaxis`. If "x2", the x
            coordinates refer to `layout.xaxis2`, and so on.
        xbins
            :class:`plotly.graph_objects.histogram.XBins` instance
            or dict with compatible properties
        xcalendar
            Sets the calendar system to use with `x` date data.
        xhoverformat
            Sets the hover text formatting rulefor `x`  using d3
            formatting mini-languages which are very similar to
            those in Python. For numbers, see:
            https://github.com/d3/d3-format/tree/v1.4.5#d3-format.
            And for dates see: https://github.com/d3/d3-time-
            format/tree/v2.2.3#locale_format. We add two items to
            d3's date formatter: "%h" for half of the year as a
            decimal number as well as "%{n}f" for fractional
            seconds with n digits. For example, *2016-10-13
            09:15:23.456* with tickformat "%H~%M~%S.%2f" would
            display *09~15~23.46*By default the values are
            formatted using `xaxis.hoverformat`.
        xsrc
            Sets the source reference on Chart Studio Cloud for
            `x`.
        y
            Sets the sample data to be binned on the y axis.
        yaxis
            Sets a reference between this trace's y coordinates and
            a 2D cartesian y axis. If "y" (the default value), the
            y coordinates refer to `layout.yaxis`. If "y2", the y
            coordinates refer to `layout.yaxis2`, and so on.
        ybins
            :class:`plotly.graph_objects.histogram.YBins` instance
            or dict with compatible properties
        ycalendar
            Sets the calendar system to use with `y` date data.
        yhoverformat
            Sets the hover text formatting rulefor `y`  using d3
            formatting mini-languages which are very similar to
            those in Python. For numbers, see:
            https://github.com/d3/d3-format/tree/v1.4.5#d3-format.
            And for dates see: https://github.com/d3/d3-time-
            format/tree/v2.2.3#locale_format. We add two items to
            d3's date formatter: "%h" for half of the year as a
            decimal number as well as "%{n}f" for fractional
            seconds with n digits. For example, *2016-10-13
            09:15:23.456* with tickformat "%H~%M~%S.%2f" would
            display *09~15~23.46*By default the values are
            formatted using `yaxis.hoverformat`.
        ysrc
            Sets the source reference on Chart Studio Cloud for
            `y`.
        zorder
            Sets the layer on which this trace is displayed,
            relative to other SVG traces on the same subplot. SVG
            traces with higher `zorder` appear in front of those
            with lower `zorder`.

Did you mean "text"?

Bad property path:
textinfo
^^^^^^^^

### 3. A relationship-based visualisation, such as a scatter plot or correlation heatmap

In [ ]:
# Heatmap to show correlations between metrics
import plotly.figure_factory as ff

cols = [
    'Passengers', 'Trips', 'Average_Delay_Minutes', 'On_Time_Percentage',
    'Ticket_Revenue_EUR', 'Operating_Cost_EUR', 'CO2_Saved_KG',
    'Energy_Consumption_KWh', 'Customer_Rating', 'Accessibility_Complaints'
]
cols = [c for c in cols if c in df_cleaned.columns]

corr = df_cleaned[cols].corr(numeric_only=True)

fig = ff.create_annotated_heatmap(
    z=corr.values,
    x=corr.columns.tolist(),
    y=corr.index.tolist(),
    colorscale="YlGnBu",
    annotation_text=[[f"{v:.2f}" for v in row] for row in corr.values],
)

fig.update_layout(
    xaxis_title="",
    yaxis_title="",
    width=900,
    height=650,
    margin=dict(l=60, r=30, t=60, b=50),
)

fig.update_traces(
    hoverinfo="z",
    showscale=True,
    colorbar=dict(title="Correlation"),
)

fig.show()

### 4. A distribution-based visualisation, such as a histogram, box plot, or violin plot

In [ ]:
# Distribution Plot - Average delay in minutes by Transport Mode
category_col = "Transport_Mode"
value_col = "Average_Delay_Minutes"

fig = px.violin(
    df_cleaned,
    x=category_col,
    y=value_col,
    color=category_col,           
    box=True,                     
    points=False,
)

fig.update_traces(
    meanline_visible=False
)

fig.update_layout(
    title="Violin Plot: Average delay in minutes by Transport Mode",
    xaxis_title="Transport Mode",
    yaxis_title="Average Delay (mins)",
)

fig.update_xaxes(tickangle=45)

fig.show()

In [ ]:
# Distribution plot - On time split by weather conditions
fig = px.violin(
    df_cleaned,
    x="Transport_Mode",
    y="On_Time_Percentage",
    color="Weather",
    box=True,          # quartile box (like inner="quartile")
    points=False,
    )

fig.update_layout(
    title="Violin Plot: On Time Percentage by Transport Mode (split by Weather)",
    xaxis_title="Transport Mode",
    yaxis_title="On Time Percentage",
    )

fig.update_traces(orientation="v")
fig.update_xaxes(tickangle=45)

fig.show()

### 5.	A performance indicator visualisation showing measures such as revenue, cost, delays, satisfaction, demand, or CO2 saved

In [ ]:
# KPI Analysis

import plotly.graph_objects as go
import plotly.subplots as sp

df_kpi = df_cleaned[
    [
        "Date",
        "Ticket_Revenue_EUR",
        "Average_Delay_Minutes",
        "Customer_Rating",
        "CO2_Saved_KG",
        "Accessibility_Complaints",
    ]
].copy()
df_kpi["Date"] = pd.to_datetime(df_kpi["Date"], errors="coerce")
df_kpi = df_kpi.dropna(subset=["Date"])

kpi = {
    "Total Revenue (€)": df_kpi["Ticket_Revenue_EUR"].sum(),
    "Avg Delay (min)": df_kpi["Average_Delay_Minutes"].mean(),
    "Avg Customer Rating": df_kpi["Customer_Rating"].mean(),
    "Total CO2 Saved (kg)": df_kpi["CO2_Saved_KG"].sum(),
    "Accessibility Complaints": df_kpi["Accessibility_Complaints"].sum(),
}

fig = sp.make_subplots(
    rows=1,
    cols=5,
    specs=[
        [
            {"type": "indicator"},
            {"type": "indicator"},
            {"type": "indicator"},
            {"type": "indicator"},
            {"type": "indicator"},
        ]
    ],
    horizontal_spacing=0.03,
)

fig.add_trace(
    go.Indicator(
        mode="number",
        value=kpi["Total Revenue (€)"],
        number={"valueformat": ",.0f"},
        title={"text": "Total Revenue (€)", "font": {"size": 14}},
    ),
    row=1,
    col=1,
)

fig.add_trace(
    go.Indicator(
        mode="number",
        value=kpi["Avg Delay (min)"],
        number={"valueformat": ".2f"},
        title={"text": "Avg Delay (min)", "font": {"size": 14}},
    ),
    row=1,
    col=2,
)

fig.add_trace(
    go.Indicator(
        mode="number",
        value=kpi["Avg Customer Rating"],
        number={"valueformat": ".2f"},
        title={"text": "Avg Customer Rating", "font": {"size": 14}},
    ),
    row=1,
    col=3,
)

fig.add_trace(
    go.Indicator(
        mode="number",
        value=kpi["Total CO2 Saved (kg)"],
        number={"valueformat": ",.0f"},
        title={"text": "Total CO2 Saved (kg)", "font": {"size": 14}},
    ),
    row=1,
    col=4,
)

fig.add_trace(
    go.Indicator(
        mode="number",
        value=kpi["Accessibility Complaints"],
        number={"valueformat": ",.0f"},
        title={"text": "Accessibility Complaints", "font": {"size": 14}},
    ),
    row=1,
    col=5,
)

fig.update_layout(
    template="plotly_white",
    height=260,
    margin=dict(l=10, r=10, t=60, b=10),
)

fig.show()

In [ ]:
if 'City' in df_cleaned.columns and 'Customer_Rating' in df_cleaned.columns:
    fig_rating_city = px.box(df_cleaned, x='City', y='Customer_Rating', color='City', points="all", title="Customer Rating Distribution by City")
    x_axis_title = "City"
    y_axis_title = "Customer Rating"
    fig_rating_city.update_layout(
        xaxis_title=x_axis_title,
        yaxis_title=y_axis_title,
        title={
            'text': "Customer Rating Distribution by City",
            'y':0.9,
            'x':0.5,
            'xanchor': 'center',
            'yanchor': 'top'},
        height=500,
        margin=dict(l=40, r=40, t=80, b=40),
    )

    fig_rating_city.update_traces(
        marker=dict(size=5, opacity=0.75),
        line=dict(width=1, color='black')
    )

    fig_rating_city.show()

In [ ]:
if 'Transport_Mode' in df_cleaned.columns and 'Customer_Rating' in df_cleaned.columns:
        fig_rating_mode = px.box(df_cleaned, x='Transport_Mode', y='Customer_Rating', color='Transport_Mode', points="all", title="Customer Rating Distribution by Transport Mode")
        x_axis_title = "Transport Mode"
        y_axis_title = "Customer Rating"
        fig_rating_mode.update_layout(
            xaxis_title=x_axis_title,
            yaxis_title=y_axis_title,
            title={
                'text': "Customer Rating Distribution by Transport Mode",
                'y':0.9,
                'x':0.5,
                'xanchor': 'center',
                'yanchor': 'top'},
            height=500,
            margin=dict(l=40, r=40, t=80, b=40),
        )

        fig_rating_mode.update_traces(
            marker=dict(size=5, opacity=0.75),
            line=dict(width=1, color='black')
        )

        fig_rating_mode.show()

In [ ]:
# Accessibility Complaints by Transport Type
if 'Transport_Mode' in df_cleaned.columns and 'Accessibility_Complaints' in df_cleaned.columns:
    fig_rating_mode = px.box(df_cleaned, x='Transport_Mode', y='Accessibility_Complaints', color='Transport_Mode', points="all", title="Customer Rating Distribution by Transport Mode")
    x_axis_title = "Transport Mode"
    y_axis_title = "Accessibility Complaints"
    fig_rating_mode.update_layout(
        xaxis_title=x_axis_title,
        yaxis_title=y_axis_title,
        title={
            'text': "Accessibility Complaints Distribution by Transport Mode",
            'y':0.9,
            'x':0.5,
            'xanchor': 'center',
            'yanchor': 'top'},
        height=500,
        margin=dict(l=40, r=40, t=80, b=40),
    )

    fig_rating_mode.update_traces(
        marker=dict(size=5, opacity=0.75),
        line=dict(width=1, color='black')
    )   

    fig_rating_mode.show()

In [ ]:
# Accessibility Complaints by City
if 'City' in df_cleaned.columns and 'Accessibility_Complaints' in df_cleaned.columns:
    fig_rating_mode = px.box(df_cleaned, x='City', y='Accessibility_Complaints', color='City', points="all", title="Customer Rating Distribution by City")
    x_axis_title = "City"
    y_axis_title = "Accessibility Complaints"
    fig_rating_mode.update_layout(
        xaxis_title=x_axis_title,
        yaxis_title=y_axis_title,
        title={
            'text': "Accessibility Complaints by City",
            'y':0.9,
            'x':0.5,
            'xanchor': 'center',
            'yanchor': 'top'},
        height=500,
        margin=dict(l=40, r=40, t=80, b=40),
    )
    fig_rating_mode.update_traces(
        marker=dict(size=5, opacity=0.75),
        line=dict(width=1, color='black')
    )
    fig_rating_mode.show()

In [ ]:
# Create a scatter plot to show the relationship between Ticket Revenue and Operating Cost by City
scatter_df = df_cleaned[["City", "Ticket_Revenue_EUR", "Operating_Cost_EUR"]]
fig_scatter = px.scatter(
    scatter_df,
    x="Ticket_Revenue_EUR",
    y="Operating_Cost_EUR",
    color="City",
    title="Ticket Revenue vs Operating Cost by City",
    labels={
        "Ticket_Revenue_EUR": "Ticket Revenue (€)",
        "Operating_Cost_EUR": "Operating Cost (€)",
        "City": "City"
    },
    template="plotly_white"
)

fig_scatter.update_traces(
    marker=dict(size=10, opacity=0.75),
    line=dict(width=1, color='black')
)

fig_scatter.update_layout(
    height=500,
    margin=dict(l=40, r=40, t=80, b=40),
    xaxis=dict(tickprefix="€", tickformat=",.0f"),
    yaxis=dict(tickprefix="€", tickformat=",.0f")
)

fig_scatter.show()

In [ ]:
# Create a chart to show the operating profit by city and transport mode
financial_df = df_cleaned[["City", "Transport_Mode", "Ticket_Revenue_EUR", "Operating_Cost_EUR"]]
financial_df["Operating_Profit_EUR"] = financial_df["Ticket_Revenue_EUR"] - financial_df["Operating_Cost_EUR"]
financial_df_grouped = financial_df.groupby(["City", "Transport_Mode"]).sum().reset_index()
fig_profit = px.bar(
    financial_df_grouped,
    x="City",
    y="Operating_Profit_EUR",
    color="Transport_Mode",
    title="Operating Profit by City and Transport Mode",
    labels={
        "Operating_Profit_EUR": "Operating Profit (€)",
        "City": "City",
        "Transport_Mode": "Transport Mode"
    },
    template="plotly_white"
)

fig_profit.update_layout(
    height=500,
    margin=dict(l=40, r=40, t=80, b=40),
    yaxis=dict(tickprefix="€", tickformat=",.0f")
)

fig_profit.show()

/var/folders/wf/_1lvp0fx2q12ycft4t95_wz00000gn/T/ipykernel_3926/2135870046.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

### 6. A dashboard visualisation combining multiple views with interactive filters

In [ ]:
#Geospatial visualisation and 3D scatter plot